list.Set( "ButtonModels", "models/SmallBridge/Other/SBconsolelow.mdl", {} )
list.Set( "ButtonModels", "models/SmallBridge/Other/SBconsole.mdl", {} )
list.Set( "ButtonModels", "models/Slyfo/powercrystal.mdl", {} )

list.Add( "OverrideMaterials", "spacebuild/Body" )
list.Add( "OverrideMaterials", "spacebuild/Hazard" )
list.Add( "OverrideMaterials", "spacebuild/Floor" )
list.Add( "OverrideMaterials", "spacebuild/SBLight" )
list.Add( "OverrideMaterials", "spacebuild/Body2" )
list.Add( "OverrideMaterials", "spacebuild/Floor2" )
list.Add( "OverrideMaterials", "spacebuild/Hazard2" )
list.Add( "OverrideMaterials", "spacebuild/Body3" )
list.Add( "OverrideMaterials", "spacebuild/Floor3" )